enyojs/ui-tests

- test/moonstone/Popup/GT-11155-DirectPopupHide-specs.js
- test/moonstone/Popup/GT-11155-DirectPopupHide.js
- test/qa/GT-11155/GT-11155-specs.js
Created test GT-11155 Popup: Direct Popup dismisses with Hide button. Fixed to not rely on Enyo Sampler.
> Gt 11155 derektor

- helpers.js
- test/moonstone/Button/GT-11181-ButtonFocusState-specs.js
- test/moonstone/Button/GT-11181-ButtonFocusState.js
> Gt 11181 derektor

- helpers.js
- test/moonstone/ProgressBar/GT-11138-ProgressButtonDigitAnimation-specs.js
- test/moonstone/ProgressBar/GT-11138-ProgressButtonDigitAnimation.js
Added GT-11138
Removed comment
> Gt 11138 derektor

- helpers.js
- test/moonstone/Drawer/GT-11186-DrawerSelectImage-specs.js
- test/moonstone/Drawer/GT-11186-DrawerSelectImage.js
Added Tests for GT-11186 Drawer: New icon and image displays simultaneously in Drawer Handle.
I tested it against custom broken versions of the code. To check if the test could catch failures such as, image not replacing and drawer not opening.
> Gt 11186 derektor

- test/moonstone/Tooltip/GT-16927-StillDisplayAfterPointerTimeout-specs.js
- test/moonstone/Tooltip/GT-16927-StillDisplayAfterPointerTimeout.js
Added Tests For GT-16927 Automation - Tooltip: Tooltip Displays after Pointer Times Out
> Gt 16927 derektor

- test/moonstone/Popup/GT-16935-ContextualPopupDisabledSpotlight-specs.js
- test/moonstone/Popup/GT-16935-ContextualPopupDisabledSpotlight.js
GT-16935: Automated - ContextualPopup: Buttons Do Not Spot outside of SpotlightModal
> GT-16935 derektor

- test/moonstone/Popup/GT-16929-FocusRemainsViaSpotlight-specs.js
- test/moonstone/Popup/GT-16929-FocusRemainsViaSpotlight.js
GT-16929 Popup: Focus remains in popup via Spotlight events
> Gt 16929 derektor

- test/moonstone/Panel/GT-11044-AlwaysViewingCollapsingPanels-specs.js
- test/moonstone/Panel/GT-11044-AlwaysViewingCollapsingPanels.js
- test/moonstone/Popup/GT-10193-ContextualPopupDisabledSpotlight-specs.js
- test/moonstone/Popup/GT-10193-ContextualPopupDisabledSpotlight.js
- test/moonstone/Popup/GT-11151-FocusRemainsViaSpotlight-specs.js
- test/moonstone/Popup/GT-11151-FocusRemainsViaSpotlight.js
- test/moonstone/Tooltip/GT-11235-StillDisplayAfterPointerTimeout-specs.js
- test/moonstone/Tooltip/GT-11235-StillDisplayAfterPointerTimeout.js
> Changed name for Jira tests/issues.

- test/moonstone/Panel/GT-11044-AlwaysViewingCollapsingPanels-specs.js
- test/moonstone/Popup/GT-10193-ContextualPopupDisabledSpotlight-specs.js
- test/moonstone/Popup/GT-11151-FocusRemainsViaSpotlight-specs.js
- test/moonstone/Popup/GT-11155-DirectPopupHide-specs.js
> renamed titles to fit standard

- README.md
Enyo-DCO-1.1-Signed-off-by: Derek Tor <derek.tor@lge.com>
> Updated Readme. Added new documentation for new helpers

- .gitignore
> Added .enyocache to gitignore.

- skeleton-specs.js
> changed skeleton specs to work with new helpers

- test/moonstone/Panel/GT-11044-AlwaysViewingCollapsingPanels-specs.js
- test/moonstone/Panel/GT-11044-AlwaysViewingCollapsingPanels/GT-11044-AlwaysViewingCollapsingPanels.js
> updated GT-11044 to use moonstone-extra version of panels

- README.md
- test/moonstone/Popup/GT-14601-ScrimPreventsFocus-specs.js
- test/moonstone/Popup/GT-14601-ScrimPreventsFocus/GT-14601-ScrimPreventsFocus.js
- test/moonstone/Popup/GT-14601-ScrimPreventsFocus/package.json
> added tests for GT-14601

- test/moonstone/Popup/GT-13951-BindingValuesChange-specs.js
- test/moonstone/Popup/GT-13951-BindingValuesChange/GT-13951-BindingValuesChange.js
- test/moonstone/Popup/GT-13951-BindingValuesChange/package.json
> added GT-13951 tests

- test/moonstone/SimplePicker/GT-13631-MarqueeStartsOn5way-specs.js
- test/moonstone/SimplePicker/GT-13631-MarqueeStartsOn5way/GT-13631-MarqueeStartsOn5way.js
- test/moonstone/SimplePicker/GT-13631-MarqueeStartsOn5way/package.json
> added test for GT-13631

- helpers.js
- test/moonstone/DatePicker/GT-17477-FormatDateES-specs.js
- test/moonstone/DatePicker/GT-17477-FormatDateES/GT-17477-FormatDateES.js
- test/moonstone/DatePicker/GT-17477-FormatDateES/package.json
getParentElement works in both chrome and webOS.
> added tests for GT-17477

- helpers.js
- test/moonstone/DatePicker/GT-17479-FormatDateHU-specs.js
- test/moonstone/DatePicker/GT-17479-FormatDateHU/GT-17479-FormatDateHU.js
- test/moonstone/DatePicker/GT-17479-FormatDateHU/package.json
getParentElement works in both chrome and webOS.
> added tests for GT-17479

- helpers.js
- test/moonstone/RadioItem/GT-17498-RadioItemRTL-specs.js
- test/moonstone/RadioItem/GT-17498-RadioItemRTL/GT-17498-RadioItemRTL.js
- test/moonstone/RadioItem/GT-17498-RadioItemRTL/package.json
Not sure of the proper way to conduct this test. Instead of toggling the locale after, I set it in the url.
> Added tests for GT-17498

- test/moonstone/SimplePicker/GT-11261-StartsWhenButtonSpotlight-specs.js
- test/moonstone/SimplePicker/GT-11261-StartsWhenButtonSpotlight/GT-11261-StartsWhenButtonSpotlight.js
- test/moonstone/SimplePicker/GT-11261-StartsWhenButtonSpotlight/package.json
> added tests for GT-11261

- README.md
- helpers.js
- test/moonstone/TimePicker/GT-11184-DurationReflectsPicker-specs.js
- test/moonstone/TimePicker/GT-11184-DurationReflectsPicker/GT-11184-DurationReflectsPicker.js
- test/moonstone/TimePicker/GT-11184-DurationReflectsPicker/package.json
> Added files and tests for GT-11184

- README.md
- helpers.js
- test/moonstone/DatePicker/GT-17477-FormatDateES-specs.js
- test/moonstone/DatePicker/GT-17478-FormatDateUS-specs.js
- test/moonstone/DatePicker/GT-17479-FormatDateHU-specs.js
Also added some semicolons to helpers.js for jshint
> changed getParentElement to enyoGetParentElementId

- test/moonstone/ExpandableListItem/GT-17041-GroupedListOnlyOneExpanded-specs.js
- test/moonstone/ExpandableListItem/GT-17041-GroupedListOnlyOneExpanded/GT-17041-GroupedListOnlyOneExpanded.js
- test/moonstone/ExpandableListItem/GT-17041-GroupedListOnlyOneExpanded/package.json
> Added tests for GT-17041

- test/moonstone/ProgressBar/GT-17161-TooltipFlipsOnSetValue-specs.js
- test/moonstone/ProgressBar/GT-17161-TooltipFlipsOnSetValue/GT-17161-TooltipFlipsOnSetValue.js
- test/moonstone/ProgressBar/GT-17161-TooltipFlipsOnSetValue/package.json
> added tests for GT-17161

- test/moonstone/ScrollerPicker/GT-14609-ScrollThumbDisabledOnHover-specs.js
- test/moonstone/ScrollerPicker/GT-14609-ScrollThumbDisabledOnHover/GT-14609-ScrollThumbDisabledOnHover.js
- test/moonstone/ScrollerPicker/GT-14609-ScrollThumbDisabledOnHover/package.json
> added test for GT-14609

- test/moonstone/ScrollerVertical/GT-18095-ScrollThumbDisplaysTopBottom-specs.js
- test/moonstone/ScrollerVertical/GT-18095-ScrollThumbDisplaysTopBottom/GT-18095-ScrollThumbDisplaysTopBottom.js
- test/moonstone/ScrollerVertical/GT-18095-ScrollThumbDisplaysTopBottom/package.json
This test relies on using https://gpro.lgsvl.com/#/c/121258/
> added tests for GT-18095

- test/moonstone/ToggleButton/GT-17493-ToggleButtonRTL-specs.js
- test/moonstone/ToggleButton/GT-17493-ToggleButtonRTL/GT-17493-ToggleButtonRTL.js
- test/moonstone/ToggleButton/GT-17493-ToggleButtonRTL/package.json
> Added tests for GT-17493

- test/moonstone/Slider/GT-18124-PopupDisplaysThroughout5way-specs.js
- test/moonstone/Slider/GT-18124-PopupDisplaysThroughout5way/GT-18124-PopupDisplaysThroughout5way.js
- test/moonstone/Slider/GT-18124-PopupDisplaysThroughout5way/package.json
> added tests for GT-18124

- test/moonstone/ToggleItem/GT-14672-KnobColorRemainsOnHover-specs.js
- test/moonstone/ToggleItem/GT-14672-KnobColorRemainsOnHover/GT-14672-KnobColorRemainsOnHover.js
- test/moonstone/ToggleItem/GT-14672-KnobColorRemainsOnHover/package.json
~~Enyo-DCO-1.1-Signed-off-by: Derek Tor derek.tor@lge.com~~
EDIT: Enyo-DCO-1.1-Signed-off-by: Derek Tor derek.tor@lgsvl.net
> added tests for GT-14672

- README.md
- helpers.js
- test/moonstone/VideoPlayer/GT-14608-SliderUpdates-specs.js
- test/moonstone/VideoPlayer/GT-14608-SliderUpdates/GT-14608-SliderUpdates.js
- test/moonstone/VideoPlayer/GT-14608-SliderUpdates/package.json
> added tests for GT-14608

- test/moonstone/DatePicker/GT-11271-DatePickerResets-specs.js
- test/moonstone/DatePicker/GT-11271-DatePickerResets/GT-11271-DatePickerResets.js
- test/moonstone/DatePicker/GT-11271-DatePickerResets/package.json
> Added tests for GT-11271

- test/moonstone/DatePicker/GT-14760-FocusDisplaysOnInteger-specs.js
- test/moonstone/DatePicker/GT-14760-FocusDisplaysOnInteger/GT-14760-FocusDisplaysOnInteger.js
- test/moonstone/DatePicker/GT-14760-FocusDisplaysOnInteger/package.json
> Added tests for GT-14760

- helpers.js
- test/moonstone/DatePicker/GT-11153-ActiveYearChanges-specs.js
- test/moonstone/DatePicker/GT-11153-ActiveYearChanges/GT-11153-ActiveYearChanges.js
- test/moonstone/DatePicker/GT-11153-ActiveYearChanges/package.json
> added tests for GT-11153

- helpers.js
- test/moonstone/DatePicker/GT-11156-ActiveMonthChanges-specs.js
- test/moonstone/DatePicker/GT-11156-ActiveMonthChanges/GT-11156-ActiveMonthChanges.js
- test/moonstone/DatePicker/GT-11156-ActiveMonthChanges/package.json
> Added tests for GT-11156

- test/moonstone/ExpandablePicker/GT-18154-FocusSpotsOnParentOnCollapse-specs.js
- test/moonstone/ExpandablePicker/GT-18154-FocusSpotsOnParentOnCollapse/GT-18154-FocusSpotsOnParentOnCollapse.js
- test/moonstone/ExpandablePicker/GT-18154-FocusSpotsOnParentOnCollapse/package.json
> added tests for GT-18154

- test/moonstone/DatePicker/GT-11271-DatePickerResets-specs.js
> updated test to use enyoGetVisibleScrollerText

- test/moonstone/ScrollerVertical/GT-14802-ScrollThumbDoesNotAppear-specs.js
- test/moonstone/ScrollerVertical/GT-14802-ScrollThumbDoesNotAppear/GT-14802-ScrollThumbDoesNotAppear.js
- test/moonstone/ScrollerVertical/GT-14802-ScrollThumbDoesNotAppear/package.json
> added files for GT-14802

- test/moonstone/VideoPlayer/GT-17318-PopupWithControlsDisplays-specs.js
- test/moonstone/VideoPlayer/GT-17318-PopupWithControlsDisplays/GT-17318-PopupWithControlsDisplays.js
- test/moonstone/VideoPlayer/GT-17318-PopupWithControlsDisplays/package.json
> added tests for GT-17318

- helpers.js
- test/moonstone/ActivityPanels/GT-14530-PanelsTransitionBackKey-specs.js
- test/moonstone/ActivityPanels/GT-14530-PanelsTransitionBackKey/GT-14530-PanelsTransitionBackKey.js
- test/moonstone/ActivityPanels/GT-14530-PanelsTransitionBackKey/package.json
TV Driver Changes that need to be merged for back() to work on webOS
https://gpro.lgsvl.com/#/c/123457/
> Added tests for GT-14530

- helpers.js
- test/moonstone/ListAction/GT-14263-ListActionCollapseOnBack-specs.js
- test/moonstone/ListAction/GT-14263-ListActionCollapseOnBack/GT-14263-ListActionCollapseOnBack.js
- test/moonstone/ListAction/GT-14263-ListActionCollapseOnBack/package.json
Relies on this change in TVdriver:
https://gpro.lgsvl.com/#/c/122698/
Cherry Picked helpers.js from GT-14530
> Added tests for GT-14263

- test/moonstone/ActivityPanels/GT-14530-PanelsTransitionBackKey-specs.js
- test/moonstone/ListAction/GT-14263-ListActionCollapseOnBack-specs.js
- test/moonstone/VideoPlayer/GT-17318-PopupWithControlsDisplays-specs.js
> updated names

- helpers.js
- test/moonstone/VideoPlayer/GT-14298-BackKeyDismissesBanners-specs.js
- test/moonstone/VideoPlayer/GT-14298-BackKeyDismissesBanners/GT-14298-BackKeyDismissesBanners.js
- test/moonstone/VideoPlayer/GT-14298-BackKeyDismissesBanners/package.json
TV Driver Changes that need to be merged for back() to work on webOS
https://gpro.lgsvl.com/#/c/123457/
> Added tests for GT-14298

- helpers.js
- test/moonstone/Panel/GT-14260-BackKeyReturnsFromVideo-specs.js
- test/moonstone/Panel/GT-14260-BackKeyReturnsFromVideo/GT-14260-BackKeyReturnsFromVideo.js
- test/moonstone/Panel/GT-14260-BackKeyReturnsFromVideo/package.json
Relies on this change in TVdriver:
https://gpro.lgsvl.com/#/c/122698/
Cherry Picker helpers.js from GT-14530
> added tests for GT-14260

- test/moonstone/Panel/GT-14260-BackKeyReturnsFromVideo-specs.js
> fixed title

- helpers.js
- test/moonstone/Popup/GT-14269-FocusReturnsContextualPopup-specs.js
- test/moonstone/Popup/GT-14269-FocusReturnsContextualPopup/GT-14269-FocusReturnsContextualPopup.js
- test/moonstone/Popup/GT-14269-FocusReturnsContextualPopup/package.json
TV Driver Changes that need to be merged for back() to work on webOS
https://gpro.lgsvl.com/#/c/123457/
> added tests GT-14269

- helpers.js
- test/moonstone/Panel/GT-14271-BackKeyPanelsTransition-specs.js
- test/moonstone/Panel/GT-14271-BackKeyPanelsTransition/GT-14271-BackKeyPanelsTransition.js
- test/moonstone/Panel/GT-14271-BackKeyPanelsTransition/package.json
TV Driver Changes that need to be merged for `back()` to work on webOS
https://gpro.lgsvl.com/#/c/123457/
> added files for GT-14271

- test/moonstone/NewDataList/GT-17240-5wayScrollVertical-specs.js
- test/moonstone/NewDataList/GT-17240-5wayScrollVertical/GT-17240-5wayScrollVertical.js
- test/moonstone/NewDataList/GT-17240-5wayScrollVertical/package.json
> added files for GT-17240

- test/moonstone/SelectableItem/GT-17267-IconsAlignWithText-specs.js
- test/moonstone/SelectableItem/GT-17267-IconsAlignWithText/GT-17267-IconsAlignWithText.js
- test/moonstone/SelectableItem/GT-17267-IconsAlignWithText/package.json
> Added files for GT-17267

- test/moonstone/NewDataList/GT-17242-5WayScrollingHorizontal-specs.js
- test/moonstone/NewDataList/GT-17242-5WayScrollingHorizontal/GT-17242-5WayScrollingHorizontal.js
- test/moonstone/NewDataList/GT-17242-5WayScrollingHorizontal/package.json
> added tests for GT-17242

- test/moonstone/NewDataList/GT-17240-5wayScrollVertical-specs.js
> renamed variable from checkTransformValue to checkThumbPosition

- helpers.js
- test/moonstone/Panel/GT-17486-FowardTransitionUsingBackKey-specs.js
- test/moonstone/Panel/GT-17486-FowardTransitionUsingBackKey/GT-17486-FowardTransitionUsingBackKey.js
- test/moonstone/Panel/GT-17486-FowardTransitionUsingBackKey/package.json
Currently fails in chrome and webOS. Which I believe is supposed to happen.
I believe it's due to this bug.
https://jira2.lgsvl.com/browse/ENYO-2369
> added tests for GT-17486

- test/moonstone/VideoPlayer/GT-18205-StatusResetsToCurrentTime-specs.js
- test/moonstone/VideoPlayer/GT-18205-StatusResetsToCurrentTime/GT-18205-StatusResetsToCurrentTime.js
- test/moonstone/VideoPlayer/GT-18205-StatusResetsToCurrentTime/package.json
> added tests for GT-18205

- test/moonstone/NewDataList/GT-17240-5wayScrollVertical-specs.js
- test/moonstone/NewDataList/GT-17242-5WayScrollingHorizontal-specs.js
- test/moonstone/Panel/GT-14271-BackKeyPanelsTransition-specs.js
- test/moonstone/Panel/GT-17486-FowardTransitionUsingBackKey-specs.js
- test/moonstone/SelectableItem/GT-17267-IconsAlignWithText-specs.js
> fixed titles with test id

- test/moonstone/NewDataList/GT-17268-StopScrollingWhenFocusOffControls-specs.js
- test/moonstone/NewDataList/GT-17268-StopScrollingWhenFocusOffControls/GT-17268-StopScrollingWhenFocusOffControls.js
- test/moonstone/NewDataList/GT-17268-StopScrollingWhenFocusOffControls/package.json
> added tests for GT-17268

- test/moonstone/LightPanel/GT-18068-CharactersDontOverlap-specs.js
- test/moonstone/LightPanel/GT-18068-CharactersDontOverlap/GT-18068-CharactersDontOverlap.css
- test/moonstone/LightPanel/GT-18068-CharactersDontOverlap/GT-18068-CharactersDontOverlap.js
- test/moonstone/LightPanel/GT-18068-CharactersDontOverlap/package.json
> added tests for GT-18068

- test/moonstone/ExpandablePicker/GT-10896-OnlyOnePickerExpands-specs.js
- test/moonstone/ExpandablePicker/GT-10896-OnlyOnePickerExpands/GT-10896-OnlyOnePickerExpands.js
- test/moonstone/ExpandablePicker/GT-10896-OnlyOnePickerExpands/package.json
> added tests for GT-10896

- test/moonstone/ListAction/GT-13637-DisabledState5Way-specs.js
- test/moonstone/ListAction/GT-13637-DisabledState5Way/GT-13637-DisabledState5Way.js
- test/moonstone/ListAction/GT-13637-DisabledState5Way/package.json
> Added tests for GT-13637

- test/moonstone/DataGridList/GT-11300-5wayOutOfContainer-specs.js
- test/moonstone/DataGridList/GT-11300-5wayOutOfContainer/GT-11300-5wayOutOfContainer.js
- test/moonstone/DataGridList/GT-11300-5wayOutOfContainer/package.json
> Added tests for GT-11300

- test/moonstone/DataGridList/GT-11300-5wayOutOfContainer-specs.js
> fixed title for GT-13637

- test/moonstone/Slider/GT-18204-SliderKnobFocusOn5way-specs.js
- test/moonstone/Slider/GT-18204-SliderKnobFocusOn5way/GT-18204-SliderKnobFocusOn5way.js
- test/moonstone/Slider/GT-18204-SliderKnobFocusOn5way/package.json
> added tests for GT-18204

- test/moonstone/VideoPlayer/GT-18076-PlaybackAfterRewindAndSkip-specs.js
- test/moonstone/VideoPlayer/GT-18076-PlaybackAfterRewindAndSkip/GT-18076-PlaybackAfterRewindAndSkip.js
- test/moonstone/VideoPlayer/GT-18076-PlaybackAfterRewindAndSkip/package.json
> Gt 18076 derektor

- test/moonstone/LightPanel/GT-17078-LightPanelFadeTransition-specs.js
- test/moonstone/LightPanel/GT-17078-LightPanelFadeTransition/GT-17078-LightPanelFadeTransition.css
- test/moonstone/LightPanel/GT-17078-LightPanelFadeTransition/GT-17078-LightPanelFadeTransition.js
- test/moonstone/LightPanel/GT-17078-LightPanelFadeTransition/package.json
- test/moonstone/VideoPlayer/GT-18076-PlaybackAfterRewindAndSkip-specs.js
> added tests for GT-17078

- test/moonstone/Popup/GT-13951-BindingValuesChange-specs.js
- test/moonstone/SimplePicker/GT-13631-MarqueeStartsOn5way-specs.js
> fixed tests for GT-13951 and GT-13631 to work better on webOS

- test/moonstone/ExpandableDataPicker/GT-14230-VisibleCheckmarksMultipleSelection-specs.js
- test/moonstone/ExpandableDataPicker/GT-14230-VisibleCheckmarksMultipleSelection/GT-14230-VisibleCheckmarksMultipleSelection.js
- test/moonstone/ExpandableDataPicker/GT-14230-VisibleCheckmarksMultipleSelection/package.json
> added tests for GT-14230

- test/moonstone/Popup/GT-13954-PopupDoesNotDismiss-specs.js
- test/moonstone/Popup/GT-13954-PopupDoesNotDismiss/GT-13954-PopupDoesNotDismiss.js
- test/moonstone/Popup/GT-13954-PopupDoesNotDismiss/package.json
> added tests for GT-13954

- test/moonstone/ActivityPanels/GT-14318-BackKeyTransitionActivityPanelVideo-specs.js
- test/moonstone/ActivityPanels/GT-14318-BackKeyTransitionActivityPanelVideo/GT-14318-BackKeyTransitionActivityPanelVideo.js
- test/moonstone/ActivityPanels/GT-14318-BackKeyTransitionActivityPanelVideo/package.json
- test/moonstone/Drawer/GT-11210-BreadcrumRetailsFalseSpotlight-specs.js
- test/moonstone/Popup/GT-13954-PopupDoesNotDismiss-specs.js
> added tests for GT-14318 and fixed description for GT-11210 and GT-13954

- test/moonstone/Button/GT-11220-SpotlightTriggeredFromPointerToKeys-specs.js
- test/moonstone/Button/GT-11220-SpotlightTriggeredFromPointerToKeys/GT-11220-SpotlightTriggeredFromPointerToKeys.js
- test/moonstone/Button/GT-11220-SpotlightTriggeredFromPointerToKeys/package.json
- test/moonstone/ScrollerVertical/GT-14792-ControlSpotsInViewportAfterScroll-specs.js
- test/moonstone/ScrollerVertical/GT-14792-ControlSpotsInViewportAfterScroll/GT-14792-ControlSpotsInViewportAfterScroll.js
- test/moonstone/ScrollerVertical/GT-14792-ControlSpotsInViewportAfterScroll/package.json
> Gt 14792 derektor

- test/moonstone/DynamicPanels/GT-18195-ListActionRetainedBackTransition-specs.js
- test/moonstone/DynamicPanels/GT-18195-ListActionRetainedBackTransition/GT-18195-ListActionRetainedBackTransition.js
- test/moonstone/DynamicPanels/GT-18195-ListActionRetainedBackTransition/package.json
> added tests for GT-18195

- test/moonstone/DynamicPanels/GT-18194-ListActionNotRetainForwardTransitions-specs.js
- test/moonstone/DynamicPanels/GT-18194-ListActionNotRetainForwardTransitions/GT-18194-ListActionNotRetainForwardTransitions.js
- test/moonstone/DynamicPanels/GT-18194-ListActionNotRetainForwardTransitions/package.json
> added tests for GT-18194

- test/moonstone/ActivityPanels/GT-14318-BackKeyTransitionActivityPanelVideo/GT-14318-BackKeyTransitionActivityPanelVideo.js
- test/moonstone/Drawer/GT-11210-BreadcrumRetailsFalseSpotlight/GT-11210-BreadcrumRetailsFalseSpotlight.js
- test/moonstone/Drawer/GT-18384-XRemainsStationary-specs.js
- test/moonstone/Drawer/GT-18384-XRemainsStationary/GT-18384-XRemainsStationary.css
- test/moonstone/Drawer/GT-18384-XRemainsStationary/GT-18384-XRemainsStationary.js
- test/moonstone/Drawer/GT-18384-XRemainsStationary/package.json
- test/moonstone/DynamicPanels/GT-18194-ListActionNotRetainForwardTransitions-specs.js
- test/moonstone/DynamicPanels/GT-18195-ListActionRetainedBackTransition-specs.js
- test/moonstone/ScrollerVertical/GT-14792-ControlSpotsInViewportAfterScroll-specs.js
- test_generator/create_test.js
> Gt 18384 derektor

- test/moonstone/ScrollerVertical/GT-14792-ControlSpotsInViewportAfterScroll-specs.js
> removed uncommented code

- test/moonstone/VideoPlayer/GT-18416-SlowRewindFowardIconsInPopup-specs.js
- test/moonstone/VideoPlayer/GT-18416-SlowRewindFowardIconsInPopup/GT-18416-SlowRewindFowardIconsInPopup.js
- test/moonstone/VideoPlayer/GT-18416-SlowRewindFowardIconsInPopup/package.json
> added tests for GT-18416

- test/moonstone/VideoPlayer/GT-18157-VideoPlaybackSeekVia5way-specs.js
- test/moonstone/VideoPlayer/GT-18157-VideoPlaybackSeekVia5way/GT-18157-VideoPlaybackSeekVia5way.js
- test/moonstone/VideoPlayer/GT-18157-VideoPlaybackSeekVia5way/package.json
> Added tests for GT-18157

- test/moonstone/VideoPlayer/GT-18156-VideoPlaybackSeekViaPointer-specs.js
- test/moonstone/VideoPlayer/GT-18156-VideoPlaybackSeekViaPointer/GT-18156-VideoPlaybackSeekViaPointer.js
- test/moonstone/VideoPlayer/GT-18156-VideoPlaybackSeekViaPointer/package.json
> Added tests for GT-18156

- test/moonstone/VideoPlayer/GT-18625-FocusSpotsNearestNeighbor-specs.js
- test/moonstone/VideoPlayer/GT-18625-FocusSpotsNearestNeighbor/GT-18625-FocusSpotsNearestNeighbor.js
- test/moonstone/VideoPlayer/GT-18625-FocusSpotsNearestNeighbor/package.json
> Added tests for GT-18625

- test/moonstone/LightPanel/GT-17078-LightPanelFadeTransition-specs.js
> added opacity checks to check for fade in

- test/moonstone/ListAction/GT-13637-DisabledState5Way-specs.js
> added longer delays for GT-13637 to be more reliable

- test/moonstone/VideoPlayer/GT-18077-PlaybackAfterFastFowardAndSkip-specs.js
- test/moonstone/VideoPlayer/GT-18077-PlaybackAfterFastFowardAndSkip/GT-18077-PlaybackAfterFastFowardAndSkip.js
- test/moonstone/VideoPlayer/GT-18077-PlaybackAfterFastFowardAndSkip/package.json
> added tests for GT-18077

- test/moonstone/ToggleButton/GT-17492-ToggleButtonRTLEllipsis-specs.js
- test/moonstone/ToggleButton/GT-17492-ToggleButtonRTLEllipsis/GT-17492-ToggleButtonRTLEllipsis.js
- test/moonstone/ToggleButton/GT-17492-ToggleButtonRTLEllipsis/package.json
> added test for GT-17492

- test/moonstone/ToggleButton/GT-17492-ToggleButtonRTLEllipsis-specs.js
> GT-17492 updated function name from checkWidth to checkForTextOverflow

- test/moonstone/VideoPlayer/GT-17167-ExpandatedStateDisplay-specs.js
- test/moonstone/VideoPlayer/GT-17167-ExpandatedStateDisplay/GT-17167-ExpandatedStateDisplay.js
- test/moonstone/VideoPlayer/GT-17167-ExpandatedStateDisplay/package.json
> added tests for GT-17167

- test/moonstone/ExpandablePicker/GT-15938-EveryWeekdayStringDisplay-specs.js
- test/moonstone/ExpandablePicker/GT-15938-EveryWeekendStringDisplay/GT-15938-EveryWeekendStringDisplay.js
- test/moonstone/ExpandablePicker/GT-15938-EveryWeekendStringDisplay/package.json
- test/moonstone/ExpandablePicker/GT-15940-EveryDayStringDisplay-specs.js
> Gt 15938 derektor

- test/moonstone/ExpandablePicker/GT-15939-EveryWeekdayStringDisplay-specs.js
- test/moonstone/ExpandablePicker/GT-15939-EveryWeekdayStringDisplay/GT-15939-EveryWeekdayStringDisplay.js
- test/moonstone/ExpandablePicker/GT-15939-EveryWeekdayStringDisplay/package.json
> Added tests for GT-15939

- test/moonstone/ExpandablePicker/GT-15936-DayPickerRemainsExpanded-specs.js
- test/moonstone/ExpandablePicker/GT-15936-DayPickerRemainsExpanded/GT-15936-DayPickerRemainsExpanded.js
- test/moonstone/ExpandablePicker/GT-15936-DayPickerRemainsExpanded/package.json
> Added tests for GT-15936

- test/moonstone/ExpandableInput/GT-17230-PasswordStaysHiddenAfterCollapse-specs.js
- test/moonstone/ExpandableInput/GT-17230-PasswordStaysHiddenAfterCollapse/GT-17230-PasswordStaysHiddenAfterCollapse.js
- test/moonstone/ExpandableInput/GT-17230-PasswordStaysHiddenAfterCollapse/package.json
> added tests for GT-17230

- test/moonstone/VideoPlayer/GT-16706-ElapsedTimeShowsInBetweenTransportSlider-specs.js
- test/moonstone/VideoPlayer/GT-16706-ElapsedTimeShowsInBetweenTransportSlider/GT-16706-ElapsedTimeShowsInBetweenTransportSlider.js
- test/moonstone/VideoPlayer/GT-16706-ElapsedTimeShowsInBetweenTransportSlider/package.json
> Added tests for GT-16706

- test/moonstone/VideoPlayer/GT-14820-IconsDisplayInPopup-specs.js
- test/moonstone/VideoPlayer/GT-14820-IconsDisplayInPopup/GT-14820-IconsDisplayInPopup.js
- test/moonstone/VideoPlayer/GT-14820-IconsDisplayInPopup/package.json
- test/moonstone/VideoPlayer/GT-16706-ElapsedTimeShowsInBetweenTransportSlider-specs.js
> added tests for GT-14820 and removed whitespace for 16706

- test/moonstone/Button/GT-16541-TranslucentButtonPressedState-specs.js
- test/moonstone/Button/GT-16541-TranslucentButtonPressedState/GT-16541-TranslucentButtonPressedState.js
- test/moonstone/Button/GT-16541-TranslucentButtonPressedState/package.json
> added tests for GT-16541

- test/moonstone/Button/GT-16542-TransparentButtonPressedState-specs.js
- test/moonstone/Button/GT-16542-TransparentButtonPressedState/GT-16542-TransparentButtonPressedState.js
- test/moonstone/Button/GT-16542-TransparentButtonPressedState/package.json
> Added tests for GT-16542

- package.json
> Updated node engine to be greater than 0.12

- tas_list.js
- tas_list.json
> added tas stuff

- test/moonstone/ExpandablePicker/GT-10896-OnlyOnePickerExpands-specs.js
- test/moonstone/ExpandablePicker/GT-10896-OnlyOnePickerExpands/GT-10896-OnlyOnePickerExpands.js
- test/moonstone/NewDataList/GT-17240-5wayScrollVertical/GT-17240-5wayScrollVertical.js
- test/moonstone/NewDataList/GT-17242-5WayScrollingHorizontal/GT-17242-5WayScrollingHorizontal.js
- test/moonstone/NewDataList/GT-17268-StopScrollingWhenFocusOffControls-specs.js
- test/moonstone/NewDataList/GT-17268-StopScrollingWhenFocusOffControls/GT-17268-StopScrollingWhenFocusOffControls.js
The problem is that enyo pack sometimes takes too long causing the dist directory not to be ready in time. This causes the tv driver to timeout. I removed some unneeded components in the tests with problems. This makes enyo-pack faster and the problems seem to have gone away.
> fixed timeout error in some tests

- test/moonstone/VideoPlayer/GT-18077-PlaybackAfterFastFowardAndSkip-specs.js
> fixed GT-18077 to reliably click buttons

- test/moonstone/ToggleButton/GT-17492-ToggleButtonRTLEllipsis-specs.js
> fixed title of GT-17492

- test/moonstone/LightPanel/GT-19111-FocusOnLastItemFromBack-specs.js
- test/moonstone/LightPanel/GT-19111-FocusOnLastItemFromBack/GT-19111-FocusOnLastItemFromBack.css
- test/moonstone/LightPanel/GT-19111-FocusOnLastItemFromBack/GT-19111-FocusOnLastItemFromBack.js
- test/moonstone/LightPanel/GT-19111-FocusOnLastItemFromBack/package.json
> added tests for GT-19111

- test/moonstone/ExpandableListItem/GT-18209-DoesNotCollapseView5wayUp-specs.js
- test/moonstone/ExpandableListItem/GT-18209-DoesNotCollapseView5wayUp/GT-18209-DoesNotCollapseView5wayUp.js
- test/moonstone/ExpandableListItem/GT-18209-DoesNotCollapseView5wayUp/package.json
> added test for GT-18209

- test/moonstone/VideoPlayer/GT-14821-TransportSliderContainsWithinIndicator-specs.js
- test/moonstone/VideoPlayer/GT-14821-TransportSliderContainsWithinIndicator/GT-14821-TransportSliderContainsWithinIndicator.js
- test/moonstone/VideoPlayer/GT-14821-TransportSliderContainsWithinIndicator/package.json
> added tests for GT-14821

- test/moonstone/Tooltip/GT-11235-StillDisplayAfterPointerTimeout-specs.js
> fixed test for GT-11235

- Gruntfile.js
- enyo-version-on-build.js
- package.json
> Added functionality for matching local enyo libraries with enyo libraries on build.

- Gruntfile.js
- enyo-version-on-build.js
> refactored enyo-version-on-build, also added new board number matcher

- Gruntfile.js
- enyo-version-on-build.js
Initially enyo-pack was running before checkout. Added in this.async() to make sure checkouts finished before enyo-pack is run.
> fixed enyo pack error

- test/moonstone/ScrollerVertical/GT-14802-ScrollThumbDoesNotAppear-specs.js
> fixed GT-14802 to match new requirements

- Gruntfile.js
- enyo-version-on-build.js
- helpers.js
This change will be temporary and is for testing purposes. It will be removed once I verify that TAS works the way it is intended to.
> logging for device on source

- test/moonstone/Popup/GT-10193-ContextualPopupDisabledSpotlight-specs.js
> fixed GT-10193 to work with new generated ids

- test/moonstone/Popup/GT-13951-BindingValuesChange-specs.js
- test/moonstone/Popup/GT-13954-PopupDoesNotDismiss-specs.js
> fixed ids for contextual popup changes

- test/moonstone/Popup/GT-14269-FocusReturnsContextualPopup-specs.js
> fixed id for GT-14269

- test/moonstone/Popup/GT-10193-ContextualPopupDisabledSpotlight-specs.js
This is a temporary change for enyo P2 TAS. Once the build updates with the newer versions then we can change it back. 
> changed ids back to previous names to work on TAS

- test/moonstone/ToggleItem/GT-14672-KnobColorRemainsOnHover-specs.js
> Fixed color variable to match new version

- test/moonstone/TimePicker/GT-11184-DurationReflectsPicker-specs.js
> Updated timepicker to work on new webOS build

- Gruntfile.js
- package.json
> added enyo:init to grunt
